# Generated by Django 4.1.7 on 2023-03-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('comercial', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13)),
                ('O_contabilidad', models.BooleanField()),
                ('estado', models.IntegerField(verbose_name=9)),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=50)),
                ('ruta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.IntegerField(verbose_name=9)),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.IntegerField(verbose_name=9)),
            ],
            options={
                'db_table': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.IntegerField(verbose_name=9)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.empresa')),
            ],
            options={
                'db_table': 'Sucursal',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('f_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.IntegerField(verbose_name=9)),
            ],
            options={
                'db_table': 'Trabajador',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('estado', models.IntegerField(verbose_name=9)),
                ('id_Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.rol')),
                ('id_Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.trabajador')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Surcursal_Permisos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('historico', models.CharField(max_length=100)),
                ('estado', models.IntegerField(verbose_name=9)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.permisos')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.sucursal')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.usuarios')),
            ],
            options={
                'db_table': 'Surcursal_Permisos',
            },
        ),
        migrations.CreateModel(
            name='Historial_Login',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dinamico.usuarios')),
            ],
            options={
                'db_table': 'Historial_Login',
            },
        ),
    ]
